from enum import Enum

class ResponseSignal(Enum):

    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_VALIDATED_SUCCESS = "FILE_VALIDATED_SUCCESS"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    DATA_PROCESSING_STARTED = "DATA_PROCESSING_STARTED"
    DATA_PROCESSING_COMPLETED = "DATA_PROCESSING_COMPLETED" 
    PROCESSING_FAILED = "PROCESSING_FAILED"
    VECTOR_STORE_CREATION_SUCCESS = "VECTOR_STORE_CREATION_SUCCESS"
    VECTOR_STORE_CREATION_FAILED = "VECTOR_STORE_CREATION_FAILED"
    EMBEDDING_SUCCESS = "EMBEDDING_SUCCESS"